# Generated by Django 5.0.6 on 2024-06-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admin_instructor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='Unknown Class', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='Unknown Course', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
